sudo: required #is required to use docker service in travis

language: python
cache:
  directories:
    - /home/travis/docker/

services:
  - docker # required, but travis uses older version of docker :(

env:
  global:
  - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
  - DOCKER_IMAGE_NAME=csv2edx
  - secure: "P/rUfNQ6pswumTXIaNYagYtYBKTV8K+59rsFS77svL1Kt2sbpAnlsMlwfFjh66LL8c+Oxx0nlCcDdceRZPendiqBV5tApJh5ne2HGJkRdMh75QMvQqwi/yekblqaZpfwR9tbRpEztbTunpR70YiueKBGu7v1PGSbuH3pVke43Tg=" #AWS_ACCESS_KEY_ID
  - secure: c633i7GyqrddeKWb54glefPP4148G0RHnEfeeVmgeLZtPitkH+ZAM9UjhBLLYvNfG8E0X9T8A8RZadmaxZfTtYwfexS7x7AlzWBzHJT1sDaRXBgn8Kxyr5cYxt5swwBstymPlgnfxA+B6CjX9OoMdjKvlU7HFqUr4SUwDaqAjiI= #AWS_SECRET_ACCESS_KEY
  - secure: "qCfWzgUMnWMA1XuPfQI+mgFXC3o8X5I6STGeqwZQeQsPtAgTo3mLeshsmg7LAmScB9MPA2J0ltnG1p4N0BJTMRvV6tesa5D8oNYqsW16MvJ+XirB6Bk3GAmbmHZ6saJJZCeRz0H6SMdrE8lQg6HltyAP94izCLBMmSlgLfUi8eI=" #AWS_ECR_REGISTRY

before_install:
  - docker --version
  - pip install awscli 
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

install:
  # Take advantage of docker caching by pulling previously built images.
  - docker build -t ${DOCKER_IMAGE_NAME}:${TRAVIS_COMMIT} --pull=true .

after_success:
  - eval $(aws ecr get-login --region eu-west-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t ${DOCKER_IMAGE_NAME} .
  - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_IMAGE_NAME}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi
  - docker tag csv2edx:latest ${AWS_ECR_REGISTRY}/${DOCKER_IMAGE_NAME}:latest
  - docker push ${AWS_ECR_REGISTRY}/${DOCKER_IMAGE_NAME}:latest
